### ISSUE TITLE
Not compatible with League Commonmark 2.x

### ISSUE THREAD

**Issue by dwightwatson** [blade-ui-kit/blade-ui-kit#101]
- Library Version: 0.2.0
- Laravel Version: 8.52.0
- PHP Version: 8.0.8

### Description:

When upgrading my dependencies, Commonmark 2.x got updated now that Laravel also supports it. This broke the markdown component as the return value has changed.

```
Next Facade\Ignition\Exceptions\ViewException: BladeUIKit\Components\Markdown\Markdown::toHtml(): Return value must be of type string, League\CommonMark\Output\RenderedContent returned (View: /Users/Dwight/Sites/hsn/vendor/blade-ui-kit/blade-ui-kit/resources/views/components/markdown/markdown.blade.php) in /Users/Dwight/Sites/hsn/vendor/blade-ui-kit/blade-ui-kit/src/Components/Markdown/Markdown.php:59
```

### Steps To Reproduce:

* Create a new Laravel app and install `blade-ui-kit`. 
* Add a markdown component to a view and render it.

```html
<x-markdown>
# 💣
</x-markdown>
```

**Comment by driesvints** [comment]
Thanks. I'll tag a release in a bit.
