### ISSUE TITLE
Dropdown not working anymore

### ISSUE THREAD

**Issue by tebeso** [blade-ui-kit/blade-ui-kit#105]
- Library Version: latest
- Laravel Version: latest
- PHP Version: 8.0.6

### Description:

Installed Laravel + Breeze. Once logged in, there is the username in the upper right corner. When i click it, a dropdown should appear. That works, but as soon as blade-ui-kit is installed, it stops working. You can click all you want, that dropdown wont appear

### Steps To Reproduce:

As described above.

**Comment by driesvints** [comment]
Please resubmit this with filled out versions. Thanks.
