### ISSUE TITLE
Breeze dropdown not working anymore

### ISSUE THREAD

**Issue by tebeso** [blade-ui-kit/blade-ui-kit#106]
- Library Version: 0.3.1
- Laravel Version: 8.16.1
- PHP Version: 8.0.6

### Description:

Installed Laravel + Breeze. Once logged in, there is the username in the upper right corner. When i click it, a dropdown should appear. That works, but as soon as blade-ui-kit is installed, it stops working. You can click all you want, that dropdown wont appear. I uninstalled blade-ui-kit and cleared the cache and it works again. Will continue without blade-ui-kit

### Steps To Reproduce:

As described above.

**Comment by driesvints** [comment]
Thanks for reporting. I'll take a look when I find some time.

**Comment by driesvints** [comment]
I can't reproduce this with the above steps sorry. The dropdown still works on latest laravel, breeze and blade ui kit.

**Comment by AyodhyaTesLK** [comment]
the reason is vendor/blade-ui-kit has another file called dropdown.blade.php. when we click the dropdown it trigger the blade ui dropdown component. to fix this you can rename breeze dropdown.blade.php component name which is located in resources/views/component

**Comment by chalenski** [comment]
> the reason is vendor/blade-ui-kit has another file called dropdown.blade.php. when we click the dropdown it trigger the blade ui dropdown component. to fix this you can rename breeze dropdown.blade.php component name which is located in resources/views/component and also change in navigation.blade.php

Yes, that's work. Thanks man.

**Comment by cpass78** [comment]
Unfortunately this problem issue persists fresh install Laravel v10.42.0 (PHP v8.1.2-1ubuntu2.14) and latest blade-ui-kit.

**Comment by adventures-in-missions** [comment]
Just encountered this issue, fresh Laravel 11 install and latest blade-ui-kit

**Comment by Hamed042gh** [comment]
its from alpine.js

**Comment by Ion901** [comment]
i changed also the dropdown.blade.php to breeze-dropdown.blade.php and changed the reference in the navigation.blade.php but also not working
