### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Ahmad-Fathy** [blade-ui-kit/blade-ui-kit#107]
- Library Version: 0.3.1
- Laravel Version: 8.54
- PHP Version: 8.0.9

### Description:
I just installed the package without any elements in blade yet
it gives me an error

`Uncaught RangeError: Maximum call stack size exceeded.`

### Steps To Reproduce:
I tried to clear cache
remove the package and clear cache then reinstall it agin
but the same issue

**Comment by driesvints** [comment]
I don't get this error sorry. Please try our Discord.
