### ISSUE TITLE
Flatpickr component broken in livewire

### ISSUE THREAD

**Issue by ades4827** [blade-ui-kit/blade-ui-kit#112]
- Library Version: 0.3.2
- Laravel Version: 8.69.0
- PHP Version: 7.4.21

### Description:
when the component is inserted into a livewire element, the date can only be selected once. livewire updates the form and clicking on the flatpickr input no longer appears the dropdown for choosing the date.

Blade UI is not designed to work with Livewire or you can integrate the following logic in the package?:
https://laravel-livewire.com/docs/2.x/alpine-js#creating-a-datepicker

thanks and congratulations for your work

### Steps To Reproduce:
`<x-flat-pickr wire:model="state.date" name="date" />`
into a livewire component and select a date. Once a value has been selected and clicked on a different html element, it is no longer possible to choose a new date

**Comment by richdynamix** [comment]
I have noticed that the flatpickr is throwing console errors when included on the page. I removed every component except this one to test and I get the following

<img width="429" alt="Screenshot 2021-11-09 at 08 42 50" src="https://user-images.githubusercontent.com/1104549/140891247-d7cc9c31-5424-4992-8c0f-e2d53232e02d.png">

This error occurs even when there is no component used in the view. @driesvints

**Comment by fallback** [comment]
@richdynamix 
Got to manage this issue by commenting the 'alpine' library commented (or removing it) from the config/blade-ui-kit.php `assets` section.
Looks like BUK fetches the Alpine even if latter is already present in `app.js`. So these two messes up with each other.
Going to check deeper and propose PR to get rid of the issue.

**Comment by scottzirkel** [comment]
I'm still seeing this behavior, but not seeing any errors in the console. I am only loading alpine (latest) through the unpgk link. I am not using `app.js` and I have the alpine section commented out in `config/blade-ui-kit.php`.

**Comment by geoffreyvanwyk** [comment]
When trying Pikaday instead of Flatpickr, the page becomes unresponsive.

**Comment by driesvints** [comment]
This one is fixed now!
