### ISSUE TITLE
Looking for a co-maintainer

### ISSUE THREAD

**Issue by driesvints** [blade-ui-kit/blade-ui-kit#118]
I'd like to start with apologising for the low attention this repo has gotten over the years. Blade UI Kit started as an ambitious project. I'd very much would like to see it continue to grow and evolve. But unfortunately I keep missing out on time to put in the work. Things like https://github.com/blade-ui-kit/blade-ui-kit/issues/116 need thorough attention and I just don't have the bandwidth atm to do that.

Therefor I'd like to search for a new co-maintainer of this library. I'm mainly looking for someone who can:

- put in attentive thoughts into the library to evolve it further
- work on new components
- keep the documentation updated
- respond and handle new issues
- review pull requests and merge them
- do new releases

You'll mostly make your own decisions on the project as I won't be involved too much anymore for the foreseeable future. I'll still update the library for new PHP and Laravel versions but that's as far as I want to go (for now).

If your interested feel free to hmu through this issue ✌️

**Comment by tshafer** [comment]
I am willing to spend a few hours a week on it. I use this package for my own projects. I have been using laravel since version 3.

**Comment by danharrin** [comment]
Hey Dries, maintainer of [Filament](https://laravel-filament.com) & co-creator of [Razor UI Blade Kit](https://razorui.com) here. I'd love to take over maintenance for the project, and I have an idea that could take the project in an exciting direction. Let me know if you're interested!

**Comment by stevebauman** [comment]
+1 for @danharrin! His commit history is greener than the Amazon forest.

**Comment by mertasan** [comment]
I already do similar work between 21:00 and 11:00 every day.

I have several open-source projects that I am developing. I am constantly developing full time open-source packages.

I can do these. I can support you.

**Comment by driesvints** [comment]
Thanks all who replied so fat! Very happy to see so many of you eager to help out : )

I'm going to leave this issue open for just a while longer and then reach a decision soon hopefully.

**Comment by leonardovee-picpay** [comment]
I would love to help maintain the project, I believe anyone who embraces this will do a good job!

**Comment by ryangjchandler** [comment]
I'd happily help out alongside @danharrin - I'd say we have a pretty good track record. 🤝

**Comment by danharrin** [comment]
> I'd happily help out alongside @danharrin - I'd say we have a pretty good track record. 🤝

I'd be open to a co-op with Ryan!

**Comment by jszobody** [comment]
I vote for @danharrin prez and @ryangjchandler vice-prez =)

**Comment by driesvints** [comment]
I'm happy to say that @danharrin & @ryangjchandler have both joined Blade UI Kit as co-maintainers. Thanks for stepping up you two 👏
