### ISSUE TITLE
Conflict with filament 3 styles

### ISSUE THREAD

**Issue by nezaboravi** [blade-ui-kit/blade-ui-kit#146]
- Library Version: 0.4.0
- Laravel Version: 10
- PHP Version: 8.2

### Description:

Here is actually two issues with markdown editor:

1 . When using it with Filament 3, styles are messed up.
2. Markdown editor appears on he page two times.

### Steps To Reproduce:
Install both Filament 3 and Blade UI Kit and add requirements in app.blade.php like so:
```
        @filamentStyles
        @filamentScripts
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @stack('styles')
        @bukStyles
```
        
Then, call for markdown editor:

`<x-easy-mde name="content" wire:model="content" />`

You will see editor DOUBLED on the page. No style applied. 

Then you remove filament styles and scripts and reload the page and you will see editor still DOUBLED, but styles are not messed up.

Images:
<img width="1643" alt="image" src="https://github.com/blade-ui-kit/blade-ui-kit/assets/1515172/422db68d-2214-4f32-a3ed-717f26bdcb9f">

Removed filament:

<img width="1702" alt="image" src="https://github.com/blade-ui-kit/blade-ui-kit/assets/1515172/6947f45d-71d7-4130-a972-37d8f156a69a">

**Comment by alexmanase** [comment]
Hi there!

Can you create a reproduction repo, would be easier for me to help you.

Thank you!

**Comment by FlickTheManual** [comment]
Library Version: 0.5.1
Laravel Version: 11
PHP Version: 8.2

## Description:

Hi, same for me, but without filament, the easy-mde make it double.

My laravel install is vanilla (I'm working on the chirps laravel bootcamp for fun) without another package than blade-ui-kit. 

The other step are the same, without filament required directive.

thanks :smile:

**Comment by FlickTheManual** [comment]
when I delete `'alpine'` from the `$assets` variable, the easy-mce editor is only displayed once, in the `blade-ui-kit/src/Components/Editors/EasyMDE.php` file. 

I continue the investigation

**Comment by FlickTheManual** [comment]
Hello everyone, 

the trix editor does the job, minus a few side effects, but I think that's more for me to dig into on this one, but here I'd rather warn you about that.

I'm still investigating easy-mde, but for the time being, if you're going to use an editor for the duration of the bug search, I'd recommend trix to do the job.

**Comment by alexmanase** [comment]
@FlickTheManual I reproduced the issue and I found out that Filament also uses Easy MDE and it has its configuration:

- https://github.com/filamentphp/filament/blob/3.x/packages/forms/resources/css/components/markdown-editor.css
- https://github.com/filamentphp/filament/blob/3.x/packages/forms/resources/js/components/markdown-editor.js

That's why it's in conflict with Filament.

@nezaboravi 

> You will see editor DOUBLED on the page. No style applied.

> Then you remove filament styles and scripts and reload the page and you will see editor still DOUBLED, but styles are not messed up.

That's because Alpine is loaded twice, first from Blade UI Kit and second from Livewire.

---

As a workaround I think it's best stick with one stack: Filament or Blade UI Kit.

**Comment by FlickTheManual** [comment]
@alexmanase thanks !

I reproduced it by  testing it in a vanilla application following the chirp laravel bootcamp, so no filament package for me ☺️

The textarea got the value, but it didn't update in livewire side.

I'll check the easymde implementation in filament, in order to see why it doesn't works normally in blade-ui

💪👍

**Comment by alexmanase** [comment]
@driesvints @FlickTheManual I think this PR(https://github.com/blade-ui-kit/blade-ui-kit/pull/159) fixes this issue.

**Comment by driesvints** [comment]
Thanks everyone! @FlickTheManual would be cool if you could verify this works now.

**Comment by FlickTheManual** [comment]
Hi @driesvints @alexmanase,

First, good job, guys, you :rock:, :rocket: 

here my chirps livewire `create.blade.php` file (like [the bootcamp in functional](https://bootcamp.laravel.com/livewire/creating-chirps) , but with the easy-mde from buk):

```blade
<?php

use function Livewire\Volt\{rules, state};

state(['message' => '']);

rules(['message' => 'required|string|max:255']);

$store = function () {

    dump($this->message); //show empty string ("")

    $validated = $this->validate();
    auth()->user()->chirps()->create($validated);
    $this->message = '';
    $this->dispatch('chirp-created');
}

?>

<div>
    <form wire:submit="store">
        <div wire:ignore>
            <x-easy-mde name="chirp"
                wire:model="message"
                class="block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-opacity-50 focus:ring-indigo-200"
                wire:key="message"
            />
        </div>
        <x-input-error :messages="$errors->get('message')" class="mt-2"></x-input-error>
        <x-primary-button class="mt-4">{{ __('Chirp') }}</x-primary-button>
    </form>
    <hr />
</div>
```

but the `dump($this->message)` show me empty string result, even the field was filled.

I don't know If I make it good, but the point is I got the easyMDE markdown field, but apparently no `message`.

Config cleared, no change in `config/blade-ui-kit`, on a newly fresh install.

Sorry guys, doesn't works at my side :sob:

**Comment by alexmanase** [comment]
I'll try to reproduce it and fix it.

**Comment by alexmanase** [comment]
@FlickTheManual please check this demo: https://github.com/alexmanase/blade-ui-kit-demo.

I used the same code from the previous comment and it worked perfectly for me.

**Comment by FlickTheManual** [comment]
@alexmanase yes, in your demo it works fine :smile: 

I inspect mine in order to know why it makes this, when the code is literally the same :sob: 

but it works from your demo, so I think it's good :smile: 

thanks for your time, guys :1st_place_medal:

**Comment by alexmanase** [comment]
Could you put your code in a demo, to take a look?
