### ISSUE TITLE
Laravel default skeleton conflict

### ISSUE THREAD

**Issue by devope** [blade-ui-kit/blade-ui-kit#148]
- Library Version: 0.4.0
- Laravel Version: 10.43.0
- PHP Version: 8.3.2

### Description:

Click on user's dropdown doesn't activate dropdown.

### Steps To Reproduce:

1) install laravel skeleton
2) install BUK
3) install laravel breeze
4) click on right user's dropdown

**Comment by alexmanase** [comment]
You have to add a prefix to the BUK config.

https://github.com/blade-ui-kit/blade-ui-kit/blob/1ba55e09f3701379872c7299a92d85a28d8d97c8/config/blade-ui-kit.php#L77

**Comment by driesvints** [comment]
Yes for this it's best to use the prefix. Thanks @alexmanase
