### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by marlonbasten** [blade-ui-kit/blade-ui-kit#150]
I cannot install Blade UI kit into a new Laravel 11 project.
Is it possible to make changes to the composer.json to fix that?

**Comment by luchaos** [comment]
You can follow this workaround in the meantime: https://github.com/blade-ui-kit/blade-ui-kit/pull/149#issuecomment-1974307484

**Comment by lorlab** [comment]
It's a pity that this package has been abandoned.  :(
