### ISSUE TITLE
Unable to install Blade UI Kit on Laravel 11 due to dependency conflict with Carbon

### ISSUE THREAD

**Issue by hemant-bacancy** [blade-ui-kit/blade-ui-kit#152]
I am encountering an installation issue while attempting to install Blade UI Kit on Laravel 11. When running `composer require blade-ui-kit/blade-ui-kit`, I receive the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires blade-ui-kit/blade-ui-kit 0.x-dev -> satisfiable by blade-ui-kit/blade-ui-kit[0.x-dev].
    - blade-ui-kit/blade-ui-kit 0.x-dev requires nesbot/carbon ^2.38 -> found nesbot/carbon[2.38.0, ..., 2.x-dev] but the package is fixed to 3.x-dev (lock file version) by a partial update and that version does not match.
```

**Steps to reproduce:**
1. Install Laravel 11.
2. Attempt to install Blade UI Kit using `composer require blade-ui-kit/blade-ui-kit`.

**Expected behavior:**
Blade UI Kit should be installed successfully on Laravel 11 without any dependency conflicts.

**Actual behavior:**
The installation fails due to a conflict with the Carbon dependency version.

**Additional context:**
- Laravel version: 11
- PHP version: 8.2

**Possible solution:**
Updating Blade UI Kit to be compatible with the latest version of Carbon (version 3.x) or providing guidance on how to resolve this dependency conflict would be greatly appreciated. Alternatively, if there's a workaround or specific version constraint that can be used with Laravel 11, please advise.

**Comment by driesvints** [comment]
Fixed. Released a Laravel v11 and Carbon v3 compatible version: v0.5.0
