### ISSUE TITLE
Project start working verry slow when you install blade ui

### ISSUE THREAD

**Issue by bobimicroweber** [blade-ui-kit/blade-ui-kit#167]
- Library Version: latest
- Laravel Version 11
- PHP Version: 8.2

### Description:
When you require blade ui kit with composer, the laravel project start working verry slowly.
I see some foreach that scan folders every time on app load..
Please look this or cache this scaned folders.
We remove this lib from our poject..

### Steps To Reproduce:
Just use laravel debugbar and see timing of application loading

**Comment by driesvints** [comment]
I'm sorry but without more info into what exactly is slow I cannot help. Feel free to re-open a new issue if you have more info around what exactly is slow, preferable with some analysis like a Blackfire report.
