### ISSUE TITLE
Implement acceptance tests

### ISSUE THREAD

**Issue by driesvints** [blade-ui-kit/blade-ui-kit#19]
To test some JS components in their behavior. Like the dropdown component.

Using Dusk? Or maybe something else? 🤔

**Comment by luttje** [comment]
Heya, first of all: thanks for this package!

The way I had to write a test for #136 felt a bit unrealistic. I feel like a headless browser test with dusk ([like Livewire does](https://github.com/livewire/livewire/tree/master/tests/Browser)) would give a more realistic and stable test-result.

If you want I can try find some time soon to make a PR that adds browser tests like it.

**Comment by driesvints** [comment]
Thanks @luttje. Right now I'm not working on this library so I wouldn't put too much time into it.
