### ISSUE TITLE
Merge config only when not cached?

### ISSUE THREAD

**Issue by bjuppa** [blade-ui-kit/blade-ui-kit#28]
Should perhaps config merging In the service provider be done only when config is not cached in the Laravel app? https://github.com/blade-ui-kit/blade-ui-kit/blob/1baaa2d04555e7060c70dc22c29d441f37dff689/src/BladeUIKitServiceProvider.php#L20

See example in [the Jetstream service provider](https://github.com/laravel/jetstream/blob/ccf7c91b868d575e202487ce73002132212d388a/src/JetstreamServiceProvider.php#L34)

**Comment by bjuppa** [comment]
I can do a PR if this idea is approved!

**Comment by driesvints** [comment]
Heya. Thanks for reporting. The service provider from Laravel already takes care of this: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/ServiceProvider.php#L65

**Comment by bjuppa** [comment]
Oh, interesting! I didn't know that cache-check was handled already... I see now it's been there for more than a year!

Also interesting that even Taylor did manual check in Jetstream. Did he forget... or just copy-paste 😄 

And @driesvints, this blade-ui-kit is a lovely idea! Having a collection of purely functional components brings so much value, just hope we can keep opinionated styling out of this one!

**Comment by driesvints** [comment]
@bjuppa thanks! :)
