### ISSUE TITLE
Flatpickr

### ISSUE THREAD

**Issue by taylormaguire** [blade-ui-kit/blade-ui-kit#39]
Would like to add Flatpickr as a Date/Time picker option. Currently used in Laravel Nova and uses vanilla javascript.

https://flatpickr.js.org/

I would be happy to PR this one if interested.

**Comment by driesvints** [comment]
Yeah I think we can add that one. Try to take inspiration from the Pikaday one on how to pass along JS options.

**Comment by taylormaguire** [comment]
awesome, i've got something started based on the pikaday component, i'll try to get that done this week. 

Thanks @driesvints!

**Comment by driesvints** [comment]
I've merged the PR that implements this and will tag a release in a bit. Thanks!

**Comment by shawndreck** [comment]
Is it possible to bind this component's v alue to LiveWire model? I am not finding any documentation on this. Please assist with any lead. Thanks

**Comment by geoffreyvanwyk** [comment]
> Is it possible to bind this component's v alue to LiveWire model? I am not finding any documentation on this. Please assist with any lead. Thanks

When you add a `wire:model` attribute to this component, the calendar dropdown will only appear the first time you click on it, but never again.
