### ISSUE TITLE
Markdown showing unescaped caracters

### ISSUE THREAD

**Issue by devingray** [blade-ui-kit/blade-ui-kit#40]
- Library Version: latest
- Laravel Version: latest
- PHP Version: 7.4

### Description:
When using the markdown from Nova like so:

<img width="790" alt="CleanShot 2020-09-03 at 17 54 08@2x" src="https://user-images.githubusercontent.com/11573528/92106440-97165f00-ee0e-11ea-970f-970d57e4d00c.png">

I render the component using `<x-markdown>{{ $markdown }}</x-markdown>`

And it renders the quotes as html unicodes

<img width="336" alt="CleanShot 2020-09-03 at 17 56 05@2x" src="https://user-images.githubusercontent.com/11573528/92106548-c0cf8600-ee0e-11ea-87a2-93d7c555903e.png">

### Steps To Reproduce:

Create markdown entry in database

use `<x-markdown>{{ $x }}</xmarkdown>`

**Comment by devingray** [comment]
Closing because I was being dumb.

**Comment by driesvints** [comment]
@devingray what happened? You had me puzzled there heh

**Comment by devingray** [comment]
I used double braces `{{ $x }}` instead of escaped braces `{!! $x  !!}`

**Comment by driesvints** [comment]
Hmm, need to try that out. Might need to update the docs. Gonna re-open to look at this later.

**Comment by devingray** [comment]
All good. I am busy updating my custom markdown converter to use this. 

Would be great in the docs to add a small section on syntax highlighting with highlight js (I believe this is what you are using along side a dark theme?)

If I just put content directly in 

```
<x-markdown flavor="github">
            # Hello
            ```php
            echo "Hello";
            return true;
            ```
        </x-markdown>
```

It works :)

**Comment by driesvints** [comment]
Syntax highlighting is more a styling thing so not really something directly for this library specifically.

**Comment by SarahSibert** [comment]
I had the same problem with this.  I think it's because in the docs it says to use:
```
<x-markdown>{{ $markdown }}</x-markdown>
```
 but to get it to work you have to use

```
<x-markdown>{!! $markdown !!}</x-markdown>
```

**Comment by driesvints** [comment]
This was indeed a docs issue. Sorry about that. I'll push a fix in a few.
