### ISSUE TITLE
Allow null values

### ISSUE THREAD

**Issue by jantbox** [blade-ui-kit/blade-ui-kit#59]
It would be nice if the input component handles null values. Now we have to construct the label like this:

<x-input name="web" :value="$brand->web ?? ''"/>

Something like this would be much cleaner:

<x-input name="web" :value="$brand->web"/>

**Comment by driesvints** [comment]
Heya thanks. An issue here was already opened: https://github.com/blade-ui-kit/blade-ui-kit/issues/58
