### ISSUE TITLE
Label component nesting

### ISSUE THREAD

**Issue by mvdnbrk** [blade-ui-kit/blade-ui-kit#62]
In HTML this is perfectly fine:

```html
<label>
    Do you like Blade UI kit?
    <input type="checkbox" name="like"> Yes, yes, yes!
</label>
```

With components someone may write:

```html
<x-label>
    Do you like Blade UI kit?
    <x-checkbox name="like"/> Yes, yes, yes!
</x-label>
```

This does not work at the moment.

1) The `for` attribute on the `label` component is required.
2) The `label` component does not support nested components at this time.

Personally I would just wrap it in a `<label>` tag, but I can Imagine someone tries to accomplish the same with the `<x-label>` syntax.

**Comment by driesvints** [comment]
I think if you don't need the `for` attribute that you'd just use the html equivalent as you wouldn't be having any benefit from the Blade UI Kit one.
