### ISSUE TITLE
Add normal button component

### ISSUE THREAD

**Issue by buismaarten** [blade-ui-kit/blade-ui-kit#64]
Might it be useful to add a normal button component?

Was building a form and I expected a button component to use like the other form components.

**Comment by driesvints** [comment]
I tried adding this before but I noticed it was pretty shallow. This belongs more in userland unless you have a very specific implementation in mind?

**Comment by buismaarten** [comment]
I was thinking about about a loading indicator (#10) so only one generic button component would be needed.
Mostly the submit type is used so that could be set by default.


These were just ideas, I haven't thought about whether it can be implemented properly.

**Comment by driesvints** [comment]
Think if you want a loading indicator button that it's best that we continue the discussion on the other issue. Thanks.
