### ISSUE TITLE
Labels values from resource files

### ISSUE THREAD

**Issue by jantbox** [blade-ui-kit/blade-ui-kit#65]
It would be great to be able to customize the value of the labels. My current label component is something like this

```
public function __construct($for, $label = '')
{
   $this->for = $for;
   $this->label = $label;

   if ($this->for === '' && $this->label !== '') {
      $this->label = Lang::has('validation.attributes.' . $this->field)
         ? Lang::get('validation.attributes.' . $this->field)
         : ucwords(str_replace('_', ' ', $this->field));
   }
}
```

**Comment by driesvints** [comment]
I think this goes a little bit beyond the component's capacity. If you need to customize its contents like that it's probably best that you create your own custom component.
