### ISSUE TITLE
[BUG] Blade Components Composition not working as documented

### ISSUE THREAD

**Issue by patrickbrouwers** [blade-ui-kit/blade-ui-kit#78]
- Library Version: 0.1.1
- Laravel Version: 8.5.0 (also tested on 8.0)
- PHP Version: 7.4.10

### Description:

I've followed the instructions about composition (https://blade-ui-kit.com/docs/0.x/introduction), but getting an unresolved dependency exception. When changing the attribute echo'ing to unescaped, the sub-component doesn't render. I'm using the latest Laravel 8 version, so I was expecting either of those 2 to work (as the "Piping Attributes" paragraph explains).

### Steps To Reproduce:

- Create `resources/views/components/forms/input.blade.php`
- Use `<x-input {{ $attributes->merge(['class' => 'p-4 text-gray-700']) }} />` as documented
- This gives exception : `Unresolvable dependency resolving [Parameter #0 [ <required> string $name ]] in class BladeUIKit\Components\Forms\Inputs\Input`

- Change to `<x-input {!! $attributes->merge(['class' => 'p-4 text-gray-700']) !!} />`
- Renders `<x-input>` instead of `<input ...>` (Thus nothing is showing in the frontend)

![Schermafbeelding 2020-09-19 om 20 45 49](https://user-images.githubusercontent.com/7728097/93686807-23847b00-fab9-11ea-90d2-62da3e828934.png)

See example repository: https://github.com/patrickbrouwers/blade-ui-kit-composition

Anything I missed? Anybody else with the same issue?

Excited to be able to use it! Hopefully we can get the composition working, because that would make it very powerful!

**Comment by driesvints** [comment]
@patrickbrouwers I discovered last week that this doesn't work like I expected it to work myself. So it's indeed not documented correctly atm. It seems you can't pipe through class constructor arguments atm. 

I'm planning to look into this soon for laravel/framework to see if we can support that out of the box in Laravel 8. Pinning this issue for now. 

I'd appreciate a PR to the docs to document it with setting the required attributes on the child element for now but no pressure of course. Thanks for the issue 👍

**Comment by patrickbrouwers** [comment]
@driesvints thanks for your answer, would be very cool if you could get it working in Laravel! Makes things a lot easier :) 
Considering you want to get this working, perhaps we could just add a note to the docs for?

**Comment by patrickbrouwers** [comment]
I can confirm `<x-input :name="$name" {{ $attributes->merge(['class' => 'p-4 text-gray-700']) }} />` works!

**Comment by patrickbrouwers** [comment]
@driesvints updated docs: https://github.com/blade-ui-kit/docs/pull/13/files
