### ISSUE TITLE
Can't use tinker on Vapor with blade ui kit installed (invalid cache path)

### ISSUE THREAD

**Issue by isaackearl** [blade-ui-kit/blade-ui-kit#89]
- Library Version: 0.3.0
- Laravel Version: 8.13.0
- PHP Version: 7.4

### Description:
When I install blade ui kit, everything works great locally and on vapor... However, for some reason I CANNOT use tinker through the vapor CLI while blade-ui-kit is installed.  I get this error:

{"output":"\n   InvalidArgumentException \n\n  Please provide a valid cache path.\n\n  at vendor\/laravel\/framework\/src\/Illuminate\/View\/Compilers\/Compiler.php:36\n     32\u2595      *\/\n     33\u2595     public function __construct(Filesystem $files, $cachePath)\n     34\u2595     {\n     35\u2595         if (! $cachePath) {\n  \u279c  36\u2595             throw new InvalidArgumentException('Please provide a valid cache path.');\n     37\u2595         }\n     38\u2595 \n     39\u2595         $this->files = $files;\n     40\u2595         $this->cachePath = $cachePath;\n\n      \u001b[2m+19 vendor frames \u001b[22m\n  20  [internal]:0\n      Illuminate\\Foundation\\Application::Illuminate\\Foundation\\{closure}(Object(BladeUI\\Icons\\BladeIconsServiceProvider))\n\n      \u001b[2m+5 vendor frames \u001b[22m\n  26  artisan:43\n      Illuminate\\Foundation\\Console\\Kernel::handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n","context":{"command":"\/opt\/bin\/php \/var\/task\/artisan tinker --execute \"phpinfo();\" --no-interaction 2>&1","aws_request_id":"8dab5f41-937a-4ea5-9141-b6431b24a416"}}
Function Logs:

### Steps To Reproduce:
install blade-ui-kit, deploy to laravel vapor, try and use 
(i'm using redis for cache)
```
vapor tinker 
```

**Comment by driesvints** [comment]
I don't have an answer right away but trying to figure this one out with @nunomaduro.

**Comment by ajuchacko91** [comment]
@isaackearl  In laravel you would get this error if there are no correct folders with permission, Not sure if that’s the problem but I would suspect it more than blade ui kit library.
cd storage
mkdir framework
cd framework
mkdir sessions
mkdir views
mkdir cache

**Comment by isaackearl** [comment]
@ajuchacko91 thanks for the tip however since this is related specifically with laravel vapor because on vapor there is no file system... Everything that is a file is uploaded to S3 and cloudfront.  That storage directory doesn't exist nor can it, unless you go out of your way to mount a permanent storage.

**Comment by leMaur** [comment]
@isaackearl Are you sure it is related to this package? Because in the error you pasted is mentioned **BladeIconsServiceProvider**, in my opinion it is related to [Blade Icons](https://github.com/blade-ui-kit/blade-icons).
Are you tried without Blade Icons?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
