### ISSUE TITLE
Style for input with error

### ISSUE THREAD

**Issue by gaetan-hexadog** [blade-ui-kit/blade-ui-kit#90]
Hi,

How can I conditionnaly apply class only if input has error ?

I'd like my input having following class in normal state:
```html
border-gray-300 focus:shadow-outline-blue focus:border-blue-300
```

and this one in error state:
```html
border-red-300 focus:shadow-outline-red focus:border-red-300
```

**Comment by driesvints** [comment]
Hey @gaetan-hexadog, this isn't really related to this project directly. Please try a support channel like the following:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by gaetan-hexadog** [comment]
Hi,

thanks but I'm pretty sure it's related to the project: If I use `x-input` how can I pass specific classes to be automatically applied if input has errors ? I can pass default classes but how can I pass classes to be used when input has errors ?

**Comment by driesvints** [comment]
@gaetan-hexadog `class` isn't an attribute specific to `x-input`. It's just piped through onto the input field. You'll face this issue in every Blade component in every Laravel app. Error state isn't tied to the input element so you'll always need a custom solution for your use case. Please try a support channel.

**Comment by gaetan-hexadog** [comment]
So what the point having an input component without any automation or addition ?
I mean, writing
```html
<x-input name="my_input" class="class-a class-b" />
```

 as no advantage than writing
```html
<input type="text" name="my_input" class="class-a class-b" />
```

**Comment by driesvints** [comment]
@gaetan-hexadog I think we disagree on that.

**Comment by gaetan-hexadog** [comment]
Can you elaborate ?

**Comment by driesvints** [comment]
The `x-input` gives you more out of the box than just the rendered input. It also provides out of the box `old` values. And it sets the `id` property so you can easily link it to a label with the same name.
