### ISSUE TITLE
Feather Icons (re-)included in the Blade UI Kit

### ISSUE THREAD

**Issue by brunocfalcao** [blade-ui-kit/blade-ui-kit#98]
### Library version

--

### Laravel version

--

### PHP version

--

### Description

Hi Dries,

I have updated my feather icons ui library to 2.0 so it´s now compatible with your 1.x version.

Is it then possible to add my feather icons library to your icons search functionality, and if not yet, can you please let me know what I need to do to make it happen?

Thank you in advance.

Rgs,
Bruno

### Steps to reproduce

--

**Comment by driesvints** [comment]
Sure. You'll need to send in a PR to the repo including your library and re-enabling it here: https://github.com/blade-ui-kit/blade-ui-kit.com/blob/main/app/Models/IconSet.php#L70-L76
