### ISSUE TITLE
Countdown Continues to Counting When It Reaches Zero

### ISSUE THREAD

**Issue by reasecret** [blade-ui-kit/blade-ui-kit#99]
On page view countdown looks like stopped at zero. But if I refresh the page countdown countinues to positive counting

[![Animation42465f33683ea5d5.gif](https://s3.gifyu.com/images/Animation42465f33683ea5d5.gif)](https://gifyu.com/image/tgIy)

I'm using component like this:
`<x-countdown :expires="new Carbon\Carbon($project->end_date)"/>`

Should I add extra code or something?

**Comment by driesvints** [comment]
That's odd. I never experienced that myself. Does a hard refresh/clearing browser cache help?

**Comment by repositoriomaster** [comment]
Hello guys!

I had the same problem and soon when I fell in love with the library.

The solution is simple.
Need to publish the vendor
"php artisan vendor:publish --tag=blade-ui-kit-config"

In "resources\views\vendor\blade-ui-kit\components\date-time\countdown.blade.php"


in line 15 codeold
`if (timeDistance < 0) {
                clearInterval(runningCounter);

                return;
            }`

Add:
`if (timeDistance < 0) {
                clearInterval(runningCounter);
                this.timer.seconds = '00';
                this.timer.minutes = '00';
                this.timer.hours = '00';
                this.timer.days = '00';
                return;
            }`

**Comment by jonnelaakso** [comment]
Hello,

Had the same problem @repositoriomaster solution fixed it.
Thank you!
